production:
  access_key_id: <%= ENV['aws_access_key_id'] %>
  secret_access_key: <%= ENV['aws_secret_access_key'] %>
  bucket: cv-red
  endpoint:
  secure: true
  private: true
  expires:
  proxy:

development:
  access_key_id: <%= ENV['aws_access_key_id'] %>
  secret_access_key: <%= ENV['aws_secret_access_key'] %>
  bucket: cv-red-dev
  endpoint:
  secure: true
  private: true
  expires:
  proxy:
